apiVersion: terraform.appvia.io/v1alpha1
kind: CloudResource
metadata:
  name: idp-dev-resources
spec:
  plan:
    name: test-idp
    revision: v0.0.1  
  providerRef:
    name: azure
  variables:
    resource_group_name: "rg-idp-terranetes-dev3"
    location: "West Europe"
    environment: "dev"
    github_repo_name: "geertvdc/idp-infrastructure-terranetes"
  
  # Terraform execution settings
  enableAutoApproval: false  # Set to true to auto-approve plans