apiVersion: terraform.appvia.io/v1alpha1
kind: Provider
metadata:
  name: github
spec:
  provider: github
  source: secret
  secretRef:
    name: github-credentials
    namespace: terranetes-system
  summary: GitHub credentials for Terranetes
